// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEidzDEc3gH3QDBgfowUqNb_uOyrcESUU',
    appId: '1:841659329811:web:47d85b2bae8d43b31d7ee6',
    messagingSenderId: '841659329811',
    projectId: 'flex-ride-c62ee',
    authDomain: 'flex-ride-c62ee.firebaseapp.com',
    storageBucket: 'flex-ride-c62ee.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8VZBU2G3aECRH1pBOdg2-77w8RK-ylYY',
    appId: '1:841659329811:android:79e0d806063e60a31d7ee6',
    messagingSenderId: '841659329811',
    projectId: 'flex-ride-c62ee',
    storageBucket: 'flex-ride-c62ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAwCHPTUBp3hYIDXtLS9hYgr5BbK7ashc',
    appId: '1:841659329811:ios:d3fe8e86b2bbafdd1d7ee6',
    messagingSenderId: '841659329811',
    projectId: 'flex-ride-c62ee',
    storageBucket: 'flex-ride-c62ee.firebasestorage.app',
    iosClientId: '841659329811-3b285s2isq7281ckstoukidju1ddo9qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAwCHPTUBp3hYIDXtLS9hYgr5BbK7ashc',
    appId: '1:841659329811:ios:d3fe8e86b2bbafdd1d7ee6',
    messagingSenderId: '841659329811',
    projectId: 'flex-ride-c62ee',
    storageBucket: 'flex-ride-c62ee.firebasestorage.app',
    iosClientId: '841659329811-3b285s2isq7281ckstoukidju1ddo9qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.flexRide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEidzDEc3gH3QDBgfowUqNb_uOyrcESUU',
    appId: '1:841659329811:web:82dce43862c2556f1d7ee6',
    messagingSenderId: '841659329811',
    projectId: 'flex-ride-c62ee',
    authDomain: 'flex-ride-c62ee.firebaseapp.com',
    storageBucket: 'flex-ride-c62ee.firebasestorage.app',
  );
}
